version: "3"
services:
  auth-db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
  auth-svc:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    env_file: ./services/auth-service/.env
    environment:
      DATABASE_URI: postgresql://postgres:password@auth-db/postgres
    ports:
      - "8000:8000"
    depends_on:
      - auth-db
    restart: "always"
  file-db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
  file-svc:
    build:
      context: ./services/file-service
      dockerfile: Dockerfile
    env_file: ./services/file-service/.env
    environment:
      DATABASE_URI: postgresql://postgres:password@file-db/postgres
      FILE_UPLOAD_DIR: /file-service/data
    ports:
      - "7000:7000"
    depends_on:
      - file-db
    restart: "always"
